name: Build, Test, and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: store_db        
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgre
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure .env
        run: cp test/.env.test test/.env

      - name: Run test
        run: go test ./test -v

  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 

      - name: Build the docker image
        run: |
          ls -la 
          docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/store-api:latest

      - name: Push the docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/store-api:latest